# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  artifactName: APP_$(Build.BuildNumber)
  branchName: main

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: NodeTool@0
  inputs:
    versionSpec: '9.x'


- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Npm-Install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run ng build --prod'
  displayName: 'Npm-Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Todo'
    publishLocation: 'Container'
  condition: succeededOrFailed()

