# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  artifactName: APP_$(Build.BuildNumber)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
    checkLatest: true

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'install dependencies'

- script: ng build --prod --configuration=dev
    displayName:'Build app for dev'
    condition:eq(variables['branchName'], 'dev')

- script: ng build --prod --configuration=staging
    displayName:'Build app for staging'
    condition:eq(variables['branchName'], 'staging')

- script: ng build --prod --configuration=production
    displayName:'Build app for production'
    condition:eq(variables['branchName'], 'main')

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: dist
    ArtifactName: $(artifactName)
    publishLocation: 'Container'
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: 'Publish artifacts'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
